-- return {
--   'atelierbram/Base2Tone-nvim',
--   config = function()
--     vim.cmd.colorscheme 'base2tone_morning_dark'
--     vim.api.nvim_set_hl(0, 'Normal', { bg = '#0A0A0A' })
--     vim.api.nvim_set_hl(0, 'NormalFloat', { bg = '#0A0A0A' })
--     vim.api.nvim_set_hl(0, 'SignColumn', { bg = '#0A0A0A' })
--     vim.api.nvim_set_hl(0, 'NormalNC', { bg = '#0A0A0A' })
--     -- Line number colors
--     vim.api.nvim_set_hl(0, 'LineNr', { fg = '#3B4048', bg = '#0A0A0A' })
--     vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#528BFF', bg = '#0A0A0A' })
--     vim.api.nvim_set_hl(0, 'TelescopeNormal', { bg = '#0C0E12' })
--     vim.api.nvim_set_hl(0, 'TelescopeBorder', { fg = '#2C313A', bg = '#0C0E12' })
--     vim.api.nvim_set_hl(0, 'TelescopePromptNormal', { bg = '#0E1014' })
--     vim.api.nvim_set_hl(0, 'TelescopePromptBorder', { fg = '#2C313A', bg = '#0E1014' })
--     vim.api.nvim_set_hl(0, 'TelescopePreviewBorder', { fg = '#2C313A', bg = '#0C0E12' })
--     vim.api.nvim_set_hl(0, 'TelescopeResultsBorder', { fg = '#2C313A', bg = '#0C0E12' })
--   end,
-- }

-- return {
--   'ricardoraposo/gruvbox-minor.nvim',
--   lazy = false,
--   priority = 1000,
--   config = function()
--     -- First set up an autocmd that will run after the colorscheme is loaded
--     vim.api.nvim_create_autocmd('ColorScheme', {
--       pattern = 'gruvbox-minor',
--       callback = function()
--         vim.api.nvim_set_hl(0, 'Normal', { bg = '#0a0a0a' })
--         vim.api.nvim_set_hl(0, 'NormalFloat', { bg = '#0a0a0a' })
--         vim.api.nvim_set_hl(0, 'SignColumn', { bg = '#0a0a0a' })
--         vim.api.nvim_set_hl(0, 'NormalNC', { bg = '#0a0a0a' })
--         vim.api.nvim_set_hl(0, 'MsgArea', { bg = '#0a0a0a' })
--         vim.api.nvim_set_hl(0, 'TelescopeBorder', { bg = '#0a0a0a' })
--         vim.api.nvim_set_hl(0, 'NvimTreeNormal', { bg = '#0a0a0a' })
--         vim.api.nvim_set_hl(0, 'EndOfBuffer', { bg = '#0a0a0a' })
--         vim.api.nvim_set_hl(0, 'StatusLine', { bg = '#0a0a0a' })
--         vim.api.nvim_set_hl(0, 'StatusLineNC', { bg = '#0a0a0a' })
--         vim.api.nvim_set_hl(0, 'VertSplit', { bg = '#0a0a0a' })
--       end,
--     })
--
--     -- Then load the colorscheme
--     vim.cmd.colorscheme 'gruvbox-minor'
--   end,
-- }
-- return {
--   'rose-pine/neovim',
--   name = 'rose-pine',
--   config = function()
--     vim.cmd 'colorscheme rose-pine'
--   end,
-- }
-- return {
--   {
--     'AlexvZyl/nordic.nvim',
--     priority = 1000,
--     opts = {
--       -- This callback can be used to override the colors used in the base palette
--       on_palette = function(palette) end,
--       -- This callback can be used to override the colors used in the extended palette
--       after_palette = function(palette) end,
--       -- This callback can be used to override highlights before they are applied
--       on_highlight = function(highlights, palette) end,
--       -- Enable bold keywords
--       bold_keywords = false,
--       -- Enable italic comments
--       italic_comments = true,
--       -- Enable editor background transparency
--       transparent = {
--         -- Enable transparent background
--         bg = true,
--         -- Enable transparent background for floating windows
--         float = false,
--       },
--       -- Enable brighter float border
--       bright_border = false,
--       -- Reduce the overall amount of blue in the theme
--       reduced_blue = true,
--       -- Swap the dark background with the normal one
--       swap_backgrounds = false,
--       -- Cursorline options. Also includes visual/selection
--       cursorline = {
--         -- Bold font in cursorline
--         bold = false,
--         -- Bold cursorline number
--         bold_number = true,
--         -- Available styles: 'dark', 'light'
--         theme = 'dark',
--         -- Blending the cursorline bg with the buffer bg
--         blend = 0.85,
--       },
--       noice = {
--         -- Available styles: 'classic', 'flat'
--         style = 'flat',
--       },
--       telescope = {
--         -- Available styles: 'classic', 'flat'
--         style = 'flat',
--       },
--       leap = {
--         -- Dims the backdrop when using leap
--         dim_backdrop = false,
--       },
--       ts_context = {
--         -- Enables dark background for treesitter-context window
--         dark_background = true,
--       },
--     },
--     config = function(_, opts)
--       require('nordic').setup(opts)
--       vim.cmd [[colorscheme nordic]]
--     end,
--   },
-- }
-- Lazy
-- return {
--   'vague2k/vague.nvim',
--   config = function()
--     -- NOTE: you do not need to call setup if you don't want to.
--     require('vague').setup {
--       -- optional configuration here
--     }
--   end,
-- }
-- return {
--   'tiagovla/tokyodark.nvim',
--   opts = {
--     -- custom options here
--     gamma = 0.9,
--   },
--   config = function(_, opts)
--     require('tokyodark').setup(opts) -- calling setup is optional
--     vim.cmd [[colorscheme tokyodark]]
--   end,
-- }
-- return { -- You can easily change to a different colorscheme.
--   -- Change the name of the colorscheme plugin below, and then
--   -- change the command in the config to whatever the name of that colorscheme is.
--   --
--   -- If you want to see what colorschemes are already installed, you can use :Telescope colorscheme.
--   'folke/tokyonight.nvim',
--   priority = 1000, -- Make sure to load this before all the other start plugins.
--   init = function()
--     -- Load the colorscheme here.
--     -- Like many other themes, this one has different styles, and you could load
--     -- any other, such as 'tokyonight-storm', 'tokyonight-moon', or 'tokyonight-day'.
--     vim.cmd.colorscheme 'tokyonight-night'
--     -- You can configure highlights by doing something like:
--     vim.cmd.hi 'Comment gui=none'
--   end,
-- }
-- return {
--   {
--     'thesimonho/kanagawa-paper.nvim',
--     lazy = false,
--     priority = 1000,
--     config = function()
--       -- Setup with desired options
--       require('kanagawa-paper').setup {
--         transparent = false, -- Enable transparent background
--         dimInactive = false, -- Disable dimming for inactive windows
--         commentStyle = { italic = true }, -- Italic comments
--         colors = {
--           palette = {
--             sumiInk0 = '#0f0f15', -- Replace with a darker color (e.g., almost black)
--           },
--         },
--         overrides = function(colors)
--           return {
--             Normal = { bg = colors.palette.sumiInk0 }, -- Ensure the background uses the new color
--             NormalFloat = { bg = colors.palette.sumiInk0 }, -- Floating windows
--             FloatBorder = { bg = colors.palette.sumiInk0 }, -- Floating window borders
--             Pmenu = { bg = colors.palette.sumiInk0 }, -- Popup menu background
--             PmenuSel = { bg = colors.palette.sumiInk1 }, -- Selected item in popup menu
--           }
--         end,
--       }
--       vim.cmd 'colorscheme kanagawa-paper' -- Apply the colorscheme
--     end,
--   },
-- }
return {
  {
    'yorumicolors/yorumi.nvim',
    priority = 1000,
    config = function()
      vim.cmd.colorscheme 'yorumi'
    end,
  },
}
